import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class profit extends javax.swing.JFrame {
      private static void setText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private Connection cn;
    private Statement st;


    /**
     * Creates new form profit
     */
    public profit() {
        initComponents();
          try{
        Class.forName("com.mysql.jdbc.Driver");
             cn = DriverManager.getConnection("jdbc:mysql://:3306/profit","root","");
             st=cn.createStatement();
             JOptionPane.showMessageDialog(null,"Connected");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"NOT Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        invesTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stuffTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        refTextField = new javax.swing.JTextField();
        profitTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sellingTextField = new javax.swing.JTextField();
        serviceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("        Calculate Monthly Profit");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 280, 24);

        nextButton.setBackground(new java.awt.Color(204, 51, 0));
        nextButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(500, 360, 63, 25);

        previousButton.setBackground(new java.awt.Color(204, 102, 0));
        previousButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton);
        previousButton.setBounds(20, 360, 91, 25);

        invesTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(invesTextField);
        invesTextField.setBounds(190, 60, 160, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SERVICE CHARGE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(31, 140, 130, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("  STUFF SALARY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 100, 130, 17);

        stuffTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(stuffTextField);
        stuffTextField.setBounds(210, 100, 140, 20);

        addButton.setBackground(new java.awt.Color(0, 204, 153));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(250, 360, 63, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("INVESTMENT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 60, 110, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("R.F.E");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 190, 41, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SELLING AMOUNT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 230, 140, 17);

        refTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(refTextField);
        refTextField.setBounds(200, 180, 140, 20);

        profitTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(profitTextField);
        profitTextField.setBounds(160, 280, 170, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PROFIT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 290, 70, 17);

        sellingTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(sellingTextField);
        sellingTextField.setBounds(210, 230, 140, 20);

        serviceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(serviceTextField);
        serviceTextField.setBounds(200, 140, 150, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\1.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
       new page1().setVisible(true);
           dispose();// TODO add your handling code here:
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
          new Start().setVisible(true);
           dispose();// TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
         String st_num1, st_num2,st_num3,st_num4,st_num5,st_num6;
        st_num1 =invesTextField.getText(); 
        st_num2 = stuffTextField.getText();
        st_num3 = serviceTextField.getText();
        st_num4 = refTextField.getText();
        st_num5 = sellingTextField.getText();
      //  st_num6 =profitTextField.getText();
        
        System.out.println("1st Value "+st_num1+" \n2nd Value "+st_num2+ "\n3rd Value"+st_num3+"\n 4th value"+st_num4+"\n5th Value"+st_num5);
        int n1,n2,n3,n4,n5,n6,res;
        n1 = Integer.parseInt(st_num1);
        n2 = Integer.parseInt(st_num2);
        n3 = Integer.parseInt(st_num3);
        n4 = Integer.parseInt(st_num4);
        n5 = Integer.parseInt(st_num5);
        //n6 = Integer.parseInt(st_num6);
        res =(((n5-(n2+n3+n4))*100)/n1);
        profitTextField.setText(""+res);
        
        
         try{
            
            String s1=invesTextField.getText();
            String s2=stuffTextField.getText();
            String s3=serviceTextField.getText();
            String s4=refTextField.getText();
            String s5=sellingTextField.getText();
            String s6=  profitTextField.getText();
            
                    
            String sql1 =   "INSERT INTO monthlyprofit(investment,salary,service,rfe,amount,profit)"+"VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"')";
            st.executeUpdate(sql1);                                                            
        }catch(SQLException ex){
            Logger.getLogger(DataofEmoloyees.class.getName()).log(Level.SEVERE,null,ex);
        
        }

    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField invesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField profitTextField;
    private javax.swing.JTextField refTextField;
    private javax.swing.JTextField sellingTextField;
    private javax.swing.JTextField serviceTextField;
    private javax.swing.JTextField stuffTextField;
    // End of variables declaration//GEN-END:variables
}
