
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
     private static void setText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private Connection cn;
    private Statement st;
    public Receipt() {
        initComponents();
         try{
        Class.forName("com.mysql.jdbc.Driver");
             cn = DriverManager.getConnection("jdbc:mysql://:3306/receipt","root","");
             st=cn.createStatement();
             JOptionPane.showMessageDialog(null,"Connected");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"NOT Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 470));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("         RECEIPT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 140, 22);

        previousButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        previousButton.setForeground(new java.awt.Color(102, 0, 102));
        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton);
        previousButton.setBounds(30, 320, 89, 25);

        NextButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NextButton.setForeground(new java.awt.Color(153, 153, 0));
        NextButton.setText("NEXT");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(380, 330, 85, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 100, 140, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 210, 110, 22);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 150, 120, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(260, 180, 120, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 70, 160, 22);

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton);
        addbutton.setBounds(180, 270, 57, 25);

        jLabel8.setText("DATE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 220, 31, 16);

        jButton1.setText("PRINT");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 270, 67, 25);

        jLabel2.setText("FOOD NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 80, 70, 16);

        jLabel7.setText("TIME");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 190, 29, 16);

        jLabel5.setText("BILL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 110, 40, 16);

        jLabel6.setText("VAT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 150, 24, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\2.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 660, 420);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 90, 41, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
         new page1().setVisible(true);
       dispose();// TODO add your handling code here:
    }//GEN-LAST:event_previousButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        new DataofEmoloyees().setVisible(true);
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_NextButtonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        try{
             String s1 = jTextField1.getText();
            String s2 = jTextField2.getText();
            String s3 = jTextField3.getText();
            String s4 = jTextField5.getText();
            String s5 = jTextField4.getText();

        
        String sql1 = "INSERT INTO details(food,bill,vat,time,Date)"+"VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"')";
            st.executeUpdate(sql1); 
        }catch(SQLException ex){
            Logger.getLogger(infohd.class.getName()).log(Level.SEVERE,null,ex);
        }
      
    }//GEN-LAST:event_addbuttonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
